name: NISOx
url: http://nisox.org

exclude: [bibble, _data_bib, README.md, Makefile, cleanupscript.py, _data]

include: [img, files]

# colorize code snippets with the pygments module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
    - {key: faculty, name: Faculty}
    - {key: postdoc, name: Researchers}
    - {key: staff, name: Staff}
    - {key: grad, name: Graduate Students}
    - {key: collab, name: Collaborators}
    - {key: alum, name: Alumni}

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: People
      link: /people
    - title: Research
      link: /research
    - title: Publications
      link: /Publications
    - title: Presentations
      link: /presentations
    - title: Software
      link: /Software
    - title: Blog
      link: https://blog.nisox.org/
